#!/bin/bash

#http://maven.ibiblio.org/maven2/asm/asm/1.3.3/maven-metadata.xml
ibib="http://maven.ibiblio.org/maven2/$1/"

if [ $# -gt 1 ]; then
    ibib="$ibib/maven-metadata.xml"
fi
echo "<!-- $ibib -->"
curl $ibib
echo
